sudo: required
services:
    - docker

before_install:
    - docker build -t jchen96/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jchen96/react-test npm run test -- --coverage

after_sucess:
    - docker build -t jchen96/multi-client ./client
    - docker build -t jchen96/multi-nginx ./nginx
    - docker build -t jchen96/multi-server ./server
    - docker build -t jchen96/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push jchen96/multi-client
    - docker push jchen96/multi-nginx
    - docker push jchen96/multi-server
    - docker push jchen96/multi-worker